sudo: false
language: "node_js"
node_js:
  - "4"
  - "6"
env:
  global:
    # GH_TOKEN and NPM_TOKEN encrypted by 'travis encrypt' utility
    - secure: "Q13UhxEZZvYtrUztXKqjL7ii62bYJfFn5Zd3/MRoGgPtWokQ9fH65fcNNbj9+q5qqsk4zIlFzXriaZLFI1cCD3CRreYIckEDqvqFs5vvaZBzEo8W7PLKpSbpw7MRCSO2mmW/g7c+4oNiDn1oaCuGV6xCX6gGXUrUKRHOKzmlnaA="
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@latest"
after_success:
  - "npm run semantic-release || true"
