environment:
  nodejs_version: "8"
cache:
  - "node_modules"
install:
  - ps: Install-Product node 8
  - "npm -g install npm@latest"
  - "set PATH=%APPDATA%\\npm;%PATH%"
  - "npm install"
build: off
test_script:
  - "node --version"
  - "npm --version"
  - "npm test"
